# Generated by Django 6.1.1 on 2026-09-25 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_options_board_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
